##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: SBDCPC
  devtools:
    add-properties: false
  profiles:
    include:
  data:
    mongodb:
      uri: "mongodb+srv://admin:admin@atlascluster.t1mywip.mongodb.net/?retryWrites=true&w=majority/database-sbdcpc"

