server:
  port: 8080
spring:
  application:
    name: "SBDCPC"
  devtools:
    add-properties: false
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://localhost:27017/sbdcpc"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
