server:
  port: 8080
spring:
  application:
    name: "SBDCPC"
  devtools:
    add-properties: false
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    virtual-host: "/"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://localhost:27017/sbdcpc"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
